### ISSUE TITLE
GitHub actions 사용하기

### ISSUE THREAD

**Issue by Perlmint** [skyser2003/ditto_bot_rust#7]
코드 퀄리티 체크는 actions자체에서 해서 보기 편하게하고 배포만 drone한테 시키기

https://docs.drone.io/api/builds/build_create/

**Comment by Perlmint** [comment]
아니면 어차피 rust crosscompile쉬우니까 actions에서 crosscompile하고 빌드 결과물 올리는게 빠를지도?

**Comment by Perlmint** [comment]
https://blog.rust-lang.org/2016/05/13/rustup.html

**Comment by skyser2003** [comment]
Actions에서 크로스 컴파일 및 도커 이미지 푸시하도록 변경하고 drone ci 사용 제거함
